-- MySQL Script generated by MySQL Workbench
-- Tue Dec 21 18:17:30 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema heroku_c679880accdf827
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema heroku_c679880accdf827
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `heroku_c679880accdf827` DEFAULT CHARACTER SET utf8 ;
USE `heroku_c679880accdf827` ;

-- -----------------------------------------------------
-- Table `heroku_c679880accdf827`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_c679880accdf827`.`comments` (
  `comment` VARCHAR(500) NULL DEFAULT NULL,
  `rating` INT(11) NULL DEFAULT NULL,
  `name` VARCHAR(50) NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `heroku_c679880accdf827`.`dessert`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_c679880accdf827`.`dessert` (
  `dessertId` INT(11) NOT NULL,
  `dessertName` VARCHAR(45) NULL DEFAULT NULL,
  `cuisine` VARCHAR(45) NULL DEFAULT NULL,
  `description` VARCHAR(500) NULL DEFAULT NULL,
  `price` DECIMAL(5,2) NULL DEFAULT NULL,
  PRIMARY KEY (`dessertId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
